name: sonarcloud
on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        projectBaseDir: src/
        args: >
          -Dsonar.organization=sivatheja70
          -Dsonar.projectKey=sivatheja70_springBootJava
          # -Dsonar.python.coverage.reportPaths=coverage.xml
          # -Dsonar.sources=lib/
          # -Dsonar.test.exclusions=tests/**
          # -Dsonar.tests=tests/
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.verbose=true
